name: bmi_calculator_app
description: A new Flutter project.

publish_to: "none"
version: 1.0.8+12

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^9.1.0
  oktoast: ^3.4.0
  shared_preferences: ^2.3.3
  # url_launcher: ^6.2.5
  #   path: deps/url_launcher/url_launcher
  logger: ^2.6.0
  encrypt:
  flutter_bloc:
  app_links: ^6.4.0
  rxdart:
  permission_handler: ^11.3.1
  file_picker: ^8.1.2
  image_picker: ^1.0.7
  fl_chart: ^0.66.2
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
# 适配鸿蒙os
dependency_overrides:
  webview_flutter:
    path: deps/webview_flutter/webview_flutter
  connectivity_plus:
    path: deps/connectivity_plus/connectivity_plus
  package_info_plus:
    path: deps/package_info_plus/package_info_plus
  device_info_plus:
    path: deps/device_info_plus/device_info_plus
  shared_preferences:
    path: deps/shared_preferences/shared_preferences
flutter:
  uses-material-design: true
  assets:
    - assets/bmi_privacy_policy.html
    - assets/ic_launcher.png
    - assets/ic_pre.png
    - assets/ic_prod.png
    - assets/ic_test.png
    - assets/ic_bw_prod.png
    - assets/ic_bw_pre.png
    - assets/ic_bw_test.png
    - assets/network_error.png
    - assets/back1.png
    - assets/back2.png
